### PR TITLE
Upgrade v0.17

### PR DESCRIPTION
**Pull request by matiasfha**
Now the loader works with elm 0.17
Still need work to make this work with https://github.com/webpack/extract-text-webpack-plugin

### CODE REVIEW

**Comment by tcoopman** [comment]
I'm very busy at the moment, but I'll try to take a look at it soon. 
Can you check why the tests fail, and see if you can fix them?

**Comment by tolgap** [comment]
@msdark You seem to have forgotten to up the `ELM_VERSION` variable inside `.travis.yml`. :)

**Comment by matiasfha** [comment]
I update the pr code but need to run the travis-ci build again..

**Comment by msdark** [comment]
test this

**Comment by stkb** [comment]
Two files have been added (maybe by mistake?): `/elm-package.json` and `/test/elm-package.json`. I don't think they're needed.

elm-css v0.5.0 doesn't support node 0.12 any more so that needs taking out of the test matrix in `.travis.yml`. 

Also the timeout for the async-mode test in `loader.js` needs bumping up even further to maybe 1000s. I tried making these changes in my own fork and Travis was all green after that.

**Comment by tcoopman** [comment]
@msdark Thanks!

**Comment by tcoopman** [comment]
released as 2.0.0

**Pull request merged**
