### PR TITLE
Update elm-css-webpack-loader for latest version of elm-css

### PR DESCRIPTION
**Pull request by roman**
Hey @tcoopman,

I went ahead and updated the example project + README to ensure everything works with the latest version of elm-css.

Can we work out a release timeline for this loader?

Thanks in advance.

### CODE REVIEW

**Comment by tcoopman** [comment]
Thanks a lot for this great pull request, I'm going to take a detailed look at it this evening. 

If everything works I'll go ahead and create a first release of the loader. Further options and features can then be added later?

**Comment by roman** [comment]
Hey @tcoopman,

No worries, thanks for getting this project started.

>  Further options and features can then be added later?

Yeah, let's not strive for perfection, ideally this is on npm soonish to remove this dependency from our vendor folder.

Cheers.

**Comment by tcoopman** [comment]
I've published 1.0.0 https://www.npmjs.com/package/elm-css-webpack-loader

**Comment by roman** [comment]
For some reason npm returns me a 404, are you experiencing the same thing?

``` bash
$ npm install --save-dev elm-css-webpack-loader
npm WARN package.json react-elm-experiment@1.0.0 No repository field.
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|npm ERR! fetch failed https://registry.npmjs.org/elm-css-webpack-loader/-/e
lm-css-webpack-loader-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

**Comment by tcoopman** [comment]
@roman I've just tested this again and it works fine for me. Maybe something was temporally wrong with npm? Can you try it again?

**Comment by roman** [comment]
Sadly, same issue.... I wonder if it is an `npm` version issue:

``` bash
$ npm install --save-dev elm-css-webpack-loader
npm WARN package.json react-elm-experiment@1.0.0 No repository field.
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|npm ERR! fetch failed https://registry.npmjs.org/elm-css-webpack-loader/-/elm-c
ss-webpack-loader-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/n
pm ERR! fetch failed https://registry.npmjs.org/elm-css-webpack-loader/-/elm-css-webpack-loader-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-n
pm ERR! fetch failed https://registry.npmjs.org/elm-css-webpack-loader/-/elm-css-webpack-loader-1.0.0.tgz
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/nix/store/c56v7xgjq3mvy3n8kdqgxf343dvxcnq7-nodejs-4.3.1/bin/node" "/nix/store/cynpv90vk7x6phcxcsav00b6
948h9fwv-elm-dev/bin/npm" "install" "--save-dev" "elm-css-webpack-loader"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! fetch failed with status code 404
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/elm/react-elm-experiment/npm-debug.log
```

**Comment by roman** [comment]
Nope... 

``` bash
npm install --save-dev elm-css-webpack-loader
npm ERR! fetch failed https://registry.npmjs.org/elm-css-webpack-loader/-/elm-css-webpack-loader-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/elm-css-webpack-loader/-/elm-css-webpack-loader-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/elm-css-webpack-loader/-/elm-css-webpack-loader-1.0.0.tgz
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/nix/store/ndwqbrlrw9iziflzabh8sy7lpc7naivk-nodejs-5.10.1/bin/node" "/nix/store/shh6s52ly5v4izizd55wakx
g90rqf90y-elm-dev/bin/npm" "install" "--save-dev" "elm-css-webpack-loader"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! fetch failed with status code 404
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/elm/react-elm-experiment/npm-debug.log
```

I wonder if it is something related to region... I'm on West Coast and can't make npm to download the package ¬¬

**Comment by roman** [comment]
Mind if I have write access to the repo? will always use PR for new dev, yet would like to be able to push tags for releases to get the npm dep via git (given that npmjs is still returning me 404)

Thanks.

**Comment by tcoopman** [comment]
@roman done. I'll do the same thing for new features, so that we can both check if we agree.

The npm thing is strange. Do you have any other issues?
I'm in Europe. I just tried again and have no issues.

**Pull request merged**
